# Set the language and python version
language: python
python:
- 2.7
- 3.6
- 3.7
- 3.8
- 3.9
install:
- pip install tox
script:
- tox
deploy:
  provider: pages
  name: Travis CI
  email: oneview-pythonsdk@hpe.com
  local_dir: docs/build/html/.
  skip_cleanup: true
  github_token: $ONEVIEW_DEPLOY_TOKEN 
  keep_history: true
  on:
    branch: master

