name: create tag and relese

on:
  pull_request:
    types: closed
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'PR')
    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@master
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          changelog_heading: "h1"
    
 
