name: create tag and relese

on:
  pull_request:
    types: closed
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'PR')
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "tag1"
          message: "Latest release"
      - uses: ncipollo/release-action@v1
        with:
          name:  ${{ steps.tag_prepare.outputs.new_tag }}
          tag: "tag1"
          body: See the <a href="https://github.com/Srija-Papinwar/Srija-Papinwar/blob/master/CHANGELOG.md">CHANGELOG.md</a> for details.
          token: ${{ secrets.TOKEN }}

      
 
