name: create tag and relese

on:
  pull_request:
    types: [closed]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'PR') && startsWith(github.base_ref, 'master')
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_and_prepare_release
        uses: moble/github-tag-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          CUSTOM_TAG: "v6.19.0"
      - name: Display
        run: echo ${{ steps.tag_and_prepare_release.outputs.new_tag }}
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          name:  ${{ steps.tag_and_prepare_release.outputs.new_tag }}
          tag: ${{ steps.tag_and_prepare_release.outputs.new_tag }}
          body: See the <a href="https://github.com/Srija-Papinwar/Srija-Papinwar/blob/master/CHANGELOG.md">CHANGELOG.md</a> for details.
          token: ${{ secrets.TOKEN }}
      
    
 
