name: create tag and relese

on:
  pull_request:
    types: closed
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'PR')
    steps:
      - name: Tag
        id: tagid
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: output
        run: echo ${{ steps.tagid.outputs.tag }}
    
 
