name: create tag and relese

on:
  pull_request:
    types: closed
jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged && startsWith(github.head_ref, 'PR')
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag
      uses: moble/github-tag-action@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: output
      run: echo ${{steps.tag.new_tag}}
 
