name: Raise a Pullrequest

on:
  push:
    branches:
    - "PR"  # Support wildcard matching

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "PR"                                 # If blank, default: triggered branch
        destination_branch: "master" # If blank, default: master
        pr_label: "automation" 
        pr_title: "Testing automation" # Title of pull request
        pr_reviewer: "nabhajit-ray,AvijitOS"
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_template: ".github/pull_request_template.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body                         
        pr_allow_empty: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
