name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        name: "Version"
        body: "Srija-Papinwar/blob/master/CHANGELOG.md"
        token: ${{ secrets.TOKEN }}